service: movie-lambda-function

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

  stage: dev
  region: ap-south-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["MovieMaster", "Arn"] }


functions:
  createMovie:
    handler: src/handlers.createMovie
    events:
      - httpApi:
          path: /movie
          method: post
  getMovie:
    handler: src/handlers.getMovie
    events:
      - httpApi:
          path: /movie/{id}
          method: get
  updateMovie:
    handler: src/handlers.updateMovie
    events:
      - httpApi:
          path: /movie/{id}
          method: put
  deleteMovie:
    handler: src/handlers.deleteMovie
    events:
      - httpApi:
          path: /movie/{id}
          method: delete
  listMovie:
    handler: src/handlers.listMovie
    events:
      - httpApi:
          path: /movies
          method: get

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    MovieMaster:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MovieMaster
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
